#!/bin/bash
#~/bin/modulecopy push
cd ./ramdisk
echo "Repacking RAMDISK..."
~/bin/romtools -rd
echo "RAMDISK repack complete."
cd ..
adb reboot bootloader
echo "Repacking BOOT.IMG..."
romtools -rp
#abootimg --create find5.custom.stock.img -f bootimg.cfg -k zImage -r bootimg.cfg
echo "BOOT.IMG repack complete."
echo "Flashing BOOT with BOOT.IMG"
fastboot flash boot boot.img
echo "Starting ADB LOGCAT"
fastboot reboot
adb logcat
